
# html lang
language: zh-CN

# main menu navigation
menu:
  首页: /
  关于: /about
  归档: /archives
  标签: /tags

# Miscelaneous
favicon: /favicon.ico

gitalk:
  enabled: true
  clientID: 6ae565c159db15a6167c
  clientSecret: 6b81331560c108209346bc4807a5126da190e14c
  repo: blogcomments
  owner: lxzmads
  admin: 
    - lxzmads
  distractionFreeMode: false